export const MANAGEMENT_PERMISSIONS = {
    USERS: {
        VIEW: 'users.view',
        CREATE: 'users.create',
        EDIT: 'users.edit',
        DELETE: 'users.delete',
        MANAGE_ROLES: 'users.manage_roles',
        MANAGE_PERMISSIONS: 'users.manage_permissions',
    },
    ANNOUNCEMENTS: {
        VIEW: 'announcements.view',
        CREATE: 'announcements.create',
        EDIT: 'announcements.edit',
        DELETE: 'announcements.delete',
        PUBLISH: 'announcements.publish',
        MODERATE: 'announcements.moderate',
    },
    EMERGENCY: {
        VIEW: 'emergency.view',
        RESPOND: 'emergency.respond',
        ACKNOWLEDGE: 'emergency.acknowledge',
        RESOLVE: 'emergency.resolve',
        MANAGE_CONTACTS: 'emergency.manage_contacts',
    },
    HELPDESK: {
        VIEW: 'helpdesk.view',
        CREATE: 'helpdesk.create',
        EDIT: 'helpdesk.edit',
        DELETE: 'helpdesk.delete',
        ASSIGN: 'helpdesk.assign',
        ESCALATE: 'helpdesk.escalate',
        RESOLVE: 'helpdesk.resolve',
    },
    MAINTENANCE: {
        VIEW: 'maintenance.view',
        CREATE: 'maintenance.create',
        EDIT: 'maintenance.edit',
        DELETE: 'maintenance.delete',
        ASSIGN: 'maintenance.assign',
        MANAGE_SCHEDULES: 'maintenance.manage_schedules',
    },
    PAYMENTS: {
        VIEW: 'payments.view',
        CREATE_BILL: 'payments.create_bill',
        EDIT_BILL: 'payments.edit_bill',
        DELETE_BILL: 'payments.delete_bill',
        MANAGE_WALLET: 'payments.manage_wallet',
        VIEW_TRANSACTIONS: 'payments.view_transactions',
        MANAGE_RECURRING: 'payments.manage_recurring',
    },
    SHIFTS: {
        VIEW: 'shifts.view',
        CREATE: 'shifts.create',
        EDIT: 'shifts.edit',
        DELETE: 'shifts.delete',
        MANAGE_SWAPS: 'shifts.manage_swaps',
        CLOCK_IN_OUT: 'shifts.clock_in_out',
    },
    TASKS: {
        VIEW: 'tasks.view',
        CREATE: 'tasks.create',
        EDIT: 'tasks.edit',
        DELETE: 'tasks.delete',
        ASSIGN: 'tasks.assign',
        COMPLETE: 'tasks.complete',
        ESCALATE: 'tasks.escalate',
    },
    CHILDREN: {
        VIEW: 'children.view',
        CREATE: 'children.create',
        EDIT: 'children.edit',
        DELETE: 'children.delete',
        APPROVE_EXIT: 'children.approve_exit',
        MANAGE_LOGS: 'children.manage_logs',
    },
    EVENTS: {
        VIEW: 'events.view',
        CREATE: 'events.create',
        EDIT: 'events.edit',
        DELETE: 'events.delete',
        MANAGE_GUESTS: 'events.manage_guests',
    },
    VISITORS: {
        VIEW: 'visitors.view',
        CREATE: 'visitors.create',
        EDIT: 'visitors.edit',
        DELETE: 'visitors.delete',
        CHECK_IN_OUT: 'visitors.check_in_out',
    },
    INVITATIONS: {
        VIEW: 'invitations.view',
        CREATE: 'invitations.create',
        RESEND: 'invitations.resend',
        REVOKE: 'invitations.revoke',
    },
} as const

export const STATUS_COLORS = {
    PENDING: 'blue',
    IN_PROGRESS: 'yellow',
    COMPLETED: 'green',
    RESOLVED: 'green',
    CLOSED: 'gray',
    CANCELLED: 'red',
    OPEN: 'blue',
    ACTIVE: 'green',
    INACTIVE: 'gray',
    DRAFT: 'gray',
    PUBLISHED: 'green',
    APPROVED: 'green',
    DENIED: 'red',
    EXPIRED: 'orange',
} as const

export const PRIORITY_COLORS = {
    LOW: 'gray',
    MEDIUM: 'blue',
    HIGH: 'orange',
    URGENT: 'red',
    CRITICAL: 'red',
} as const

export const PRIORITY_ICONS = {
    LOW: 'arrow-down',
    MEDIUM: 'minus',
    HIGH: 'arrow-up',
    URGENT: 'alert-triangle',
    CRITICAL: 'alert-circle',
} as const

export const STATUS_LABELS = {
    PENDING: 'Pending',
    IN_PROGRESS: 'In Progress',
    COMPLETED: 'Completed',
    RESOLVED: 'Resolved',
    CLOSED: 'Closed',
    CANCELLED: 'Cancelled',
    OPEN: 'Open',
    ACTIVE: 'Active',
    INACTIVE: 'Inactive',
    DRAFT: 'Draft',
    PUBLISHED: 'Published',
    APPROVED: 'Approved',
    DENIED: 'Denied',
    EXPIRED: 'Expired',
    ON_HOLD: 'On Hold',
    NO_SHOW: 'No Show',
} as const

export const PRIORITY_LABELS = {
    LOW: 'Low',
    MEDIUM: 'Medium',
    HIGH: 'High',
    URGENT: 'Urgent',
    CRITICAL: 'Critical',
} as const
